### ISSUE TITLE
Add confirmation on public key retrieval

### ISSUE THREAD

**Issue by erdnaxe** [NicsTr/age-plugin-ledger#1]
Currently the app does not prompt on public key retrieval.

Proposition :
- Implement a new command `ConfirmRecipient` that:
  - send an identity to Ledger Nano,
  - returns the public key and `90 00` only if it matches the Ledger Nano public key.
- Add prompt on command `GetRecipient` (`02`)

**Comment by NicsTr** [comment]
Done in dcf11249d09c81e30578021bbc3b96552ed78e1a and [app-age/434ab54](https://github.com/Ledger-Donjon/app-age/commit/434ab5495e43c73d6cfc982e35f0f881c7cb456f).

Thanks.
